### ISSUE TITLE
DuckDB `0.10.3` Not Available in Maven Central

### ISSUE THREAD

**Issue by brianwyka** [duckdb/duckdb-java#11]
Happened before...

https://github.com/duckdb/duckdb/issues/11244

**Comment by zhicwu** [comment]
In GitHub Actions, it appears that a manual intervention is needed from @hannes to release the artifacts from Sonatype's staging repository.

**Comment by hannes** [comment]
Indeed will have a look

**Comment by hannes** [comment]
Should be uploaded

**Comment by elefeint** [comment]
Thank you (tested, works great)!
Will you also be uploading the built drivers to https://github.com/duckdb/duckdb-java/releases/tag/v0.10.3 github artifacts?
