### ISSUE TITLE
JVM SIGSEGV crash while getting connection to duckdb server

### ISSUE THREAD

**Issue by shreyasGit** [duckdb/duckdb-java#15]
### What happens?

I am using java JDBC API to connect to DUCKDB - am using dependency version -i intend to use HTTPFS extention to read and write parquet files to s3.

```
 <dependency>
    <groupId>org.duckdb</groupId>
    <artifactId>duckdb_jdbc</artifactId>
    <version>0.8.1</version>
</dependency>
```
i am running the following code as part of a container image based on alpine Zulu 13 JRE
when i execute the following code - I get an SIGSEGV crash

```
Class.forName("org.duckdb.DuckDBDriver");
	   logger.info("Driver loaded");
	   Connection conn = null;
	   try {
	    conn = DriverManager.getConnection("jdbc:duckdb:");
	   }
	   catch (SQLException e ) {
		logger.error(e.getMessage() + e.getStackTrace());
	}`

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000063bdc6, pid=1, tid=134
#
# JRE version: OpenJDK Runtime Environment Zulu13.54+17-CA (13.0.14+5) (build 13.0.14+5-MTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu13.54+17-CA (13.0.14+5-MTS, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  0x000000000063bdc6
#
# Core dump will be written. Default location: /install/citng/service/core.1
#
# An error report file with more information is saved as:
# /install/citng/service/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```
this code works fine on my windows machine running java.
earlier i had glibc issues on alpine - java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java4480084372361105472.so: Error loading shared library ld-linux-x86-64.so.2:
so i installed RUN apk update && apk add --no-cache libc6-compat and error for UnsatisfiedLink error was eliminated.
Now i get an jvm crash, i observe it does not write crash report as well.

### To Reproduce

1. use java client library of version 0.8.1
2. have a simple code to get connection from db -
3. conn = DriverManager.getConnection("jdbc:duckdb:");
4. run this in a Linux alpine environment
5. observe the error
Thanks

### OS:

Alpine linux - X86_64

### DuckDB Version:

0.8.1

### DuckDB Client:

Java

### Full Name:

Shreyas Deshpande

### Affiliation:

SAS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Given the original issue here was with trying to use DuckDB on musl/alpine based systems, which we don't support, I'm going to close this issue
