### ISSUE TITLE
Failed to run on amazoncorretto:17-alpine inside docker container

### ISSUE THREAD

**Issue by Klassen-Olga** [duckdb/duckdb-java#22]
Given the Dockerfile

```
FROM amazoncorretto:17-alpine

RUN apk add g++ git make cmake ninja openssl-dev gcc gcompat

ADD build/libs/source.jar app.jar

ENTRYPOINT [ "sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
```

Getting:

Invalid Error: No error information
at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:48)
at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:41)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)

To reproduce:
build.gradle.kt
`implementation("org.duckdb:duckdb_jdbc:0.10.3")
` 
in the Main.kt

```
val sql =
    """
    INSTALL aws;
    LOAD aws;
    INSTALL httpfs;
    LOAD httpfs;
    install spatial;
    load spatial;
    CALL load_aws_credentials();
    SET s3_region = 'xxx';
    """.trimIndent()

 val conn = DriverManager.getConnection("jdbc:duckdb:") as DuckDBConnection
        conn.createStatement().use { stmt ->
            stmt.execute(sql)

            stmt.executeQuery(
                "select rawId, st_geomfromwkb(geometry) as transformed_geometry from 's3://xx/file.parquet';",
            ).use { rs ->
                while (rs.next()) {
                    rs.getObject(2)
                    println("Raw it ${rs.getString(1)} has the following coordinates ${rs.getObject(2)}")
                }
            }
        }
```

**Comment by Mause** [comment]
Hi there, we don't presently support musl or alpine based systems at the moment. If you want to use DuckDB you'll need to either compile it yourself or switch to a different container

**Comment by tculp** [comment]
Could we add that info to the installation docs page? https://duckdb.org/docs/installation/index?version=stable&environment=java&download_method=package_manager

There is no mention of the base OS mattering for the java installation, and we also were running into this issue since alpine images are commonplace in the container ecosystem

**Comment by Mause** [comment]
Yeah we probably need a link to the support policy:

> We can only support the following platforms: Windows 10+ on x86_64, macOS latest, Linux x86_64 & aarch64, mainstream distros under support by distributor running with glibc (Ubuntu LTS is a safe bet).

https://duckdblabs.com/news/2023/10/02/support-policy.html
