### ISSUE TITLE
Can't install DuckDB 1.0.1 nightly build in Dbeaver

### ISSUE THREAD

**Issue by ericemc3** [duckdb/duckdb-java#54]
I'd like to benefit from DuckDB last functionalities but can't manage to install nightly build from https://artifacts.duckdb.org/latest/java-jars.zip

DBeaver Version
Community Edition 24.1.2

Operating System
Win 11

Steps to reproduce
1 - disconnect the database
2 - add new driver in the driver editor, then delete previous (Maven) ones
![image](https://github.com/duckdb/duckdb-java/assets/17407796/e8ab9dba-f211-4ed0-b5c1-e4f517f1ede0)
![image](https://github.com/duckdb/duckdb-java/assets/17407796/2660862d-6acb-43a6-9e07-7382c9a49fa4)
3 - connect the database
4 - PRAGMA VERSION -> 0.10.3 dev
![image](https://github.com/duckdb/duckdb-java/assets/17407796/819442fd-e5d4-49e4-a36a-f28dbeb4789c)

**Comment by Mause** [comment]
You need to remove the "RELEASE" version in the libraries list before it will use the one you manually specify (alternatively, you can use maven to add the newer version).
