### ISSUE TITLE
Union_by_name parallelism release dates [v1.1.0]

### ISSUE THREAD

**Issue by simran99** [duckdb/duckdb-java#76]
Hi Team,

Could you please confirm if the release date of 1.1.0 is confirmed to be 2nd September 2024 as stated here - https://duckdb.org/docs/dev/release_calendar.html ? 
 
Also could you please confirm if these changes - https://github.com/duckdb/duckdb/pull/12957 will be part of **1.1.0 version of duckdb-java** ?

**Comment by carlopi** [comment]
Matching is that release X of duckdb-java contain duckdb library as it was in release X.

So given that particular PR is part of DuckDB v1.1.0, it's also part of duckdb-java v1.1.0.

DuckDB-Java releases might be up to a few days later than DuckDB releases.
