### ISSUE TITLE
DuckDB (on Java) produces different results on Linux vs. MacOS vs. Windows?

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb-java#77]
Greetings,

please see https://github.com/starlake-ai/jsqltranspiler
We have a test suite of 600 very simple, self containing SQL tests, which we verify against static expected results.

This test suite works reliable on Linux, different machines.
But a few tests fail reliably  on Windows or MacOS, even with the following explicit properties:
```
    Properties info = new Properties();
    info.put("old_implicit_casting", "true");
    info.put("default_null_order", "NULLS FIRST");
    info.put("default_order", "ASC");
    info.put("memory_limit", "1GB");
```

What can cause such a different behaviour please?

**Comment by Mause** [comment]
Can you provide samples of the queries or code that behaves differently depending on platform please?

**Comment by manticore-projects** [comment]
Greetings. I can't remember, how exactly this got solved but it's not any issue anymore. Sorry for bothering.
