### ISSUE TITLE
duckdb java version 1.1.1

### ISSUE THREAD

**Issue by sullis** [duckdb/duckdb-java#91]
Has there been a new release (1.1.1) of the Java library?

<img width="307" alt="image" src="https://github.com/user-attachments/assets/46b06c70-e276-476e-bf05-47da94952949">

I do not see version 1.1.1 in Maven Central 

https://repo1.maven.org/maven2/org/duckdb/duckdb_jdbc/

<img width="756" alt="image" src="https://github.com/user-attachments/assets/e3a97e06-8658-4884-b614-37ce701bfb52">

**Comment by carlopi** [comment]
v1.1.1 is on Maven Central now.
