### ISSUE TITLE
SIGSEGV in TemplatedMatch

### ISSUE THREAD

**Issue by wdroste** [duckdb/duckdb-java#93]
### What happens?

We've been unable to isolate the particular query that is causing this crash, however here's the stack.

We're getting a SIGSEV on TemplateMatch code. Attached will be the hs_err file coming from Java.

Version: v0.10.0
OS: Linux Ubuntu 22.04.5

### To Reproduce

We've not been able to isolate the query that causes this, basically it seemed to happen under load.

### OS:

Linux Ubuntu 22.04.5

### DuckDB Version:

0.10.0

### DuckDB Client:

Java Zulu JDK 11

### Hardware:

Intel

### Full Name:

Will Droste

### Affiliation:

Brinqa

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
I see, so `TemplatedMatch` is the name
Perhaps related to <https://github.com/duckdb/duckdb/pull/8979> then
